// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Word Hunter",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Word Hunter",
            targets: ["AppModule"],
            bundleIdentifier: "com.victorfriedrich.learnswift",
            teamIdentifier: "US68GNF8W5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Take images to collect words"),
                .locationWhenInUse(purposeString: "Tags each captured word with where you found it, so your collection remembers the place and two location-based achievements can unlock.")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/weichsel/ZIPFoundation.git", "0.9.20"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ZIPFoundation", package: "zipfoundation")
            ],
            path: "."
        )
    ]
)